import type { Appointment, Doctor } from "./type"

export const mockAppointments: Appointment[] = [
  {
    id: "1",
    date: "Thứ 4, 28/04/2024",
    time: "8:00 - 8:30 AM",
    doctorName: "ThS BS. Trần Ngọc Anh Thơ",
    specialty: "Da khoa",
    imageUrl: "/placeholder.svg?height=60&width=60",
    status: "upcoming",
    department: "Da khoa",
    room: "Phòng 45 - Tầng 2 Khu A",
    queueNumber: 12,
    patientName: "LÊ THIỆN NHI",
    patientBirthday: "28/04/2004",
    patientGender: "Nữ",
    patientLocation: "Cà Mau",
    appointmentFee: "150.000 VND",
    codes: {
      appointmentCode: "312893713",
      transactionCode: "31283781293713",
      patientCode: "47298347293847",
    },
  },
  {
    id: "2",
    date: "Thứ bảy, 02/05/2024",
    time: "8:00 - 8:30 AM",
    doctorName: "BSCKI. Huỳnh Văn Thiều",
    specialty: "Sản nhi",
    imageUrl: "/placeholder.svg?height=60&width=60",
    status: "upcoming",
    department: "Sản nhi",
    room: "Phòng 66 - Tầng 1 Khu B",
    queueNumber: 8,
    patientName: "LÊ THIỆN NHI",
    patientBirthday: "28/04/2004",
    patientGender: "Nữ",
    patientLocation: "Cà Mau",
    appointmentFee: "150.000 VND",
    codes: {
      appointmentCode: "312893713",
      transactionCode: "31283781293713",
      patientCode: "47298347293847",
    },
  },
  {
    id: "3",
    date: "Thứ bảy, 02/05/2024",
    time: "8:00 - 8:30 AM",
    doctorName: "BSCKI. Huỳnh Văn Thiều",
    specialty: "Sản nhi",
    imageUrl: "/placeholder.svg?height=60&width=60",
    status: "upcoming",
    department: "Sản nhi",
    room: "Phòng 66 - Tầng 1 Khu B",
    queueNumber: 8,
    patientName: "LÊ THIỆN NHI",
    patientBirthday: "28/04/2004",
    patientGender: "Nữ",
    patientLocation: "Cà Mau",
    appointmentFee: "150.000 VND",
    codes: {
      appointmentCode: "312893713",
      transactionCode: "31283781293713",
      patientCode: "47298347293847",
    },
  },
  {
    id: "4",
    date: "Thứ 2, 15/04/2024",
    time: "9:00 - 9:30 AM",
    doctorName: "BSCKII. Trần Đỗ Phương Nhi",
    specialty: "Tim mạch",
    imageUrl: "/placeholder.svg?height=60&width=60",
    status: "completed",
    department: "Tim mạch",
    room: "Phòng 32 - Tầng 3 Khu C",
    queueNumber: 5,
    patientName: "LÊ THIỆN NHI",
    patientBirthday: "28/04/2004",
    patientGender: "Nữ",
    patientLocation: "Cà Mau",
    appointmentFee: "200.000 VND",
    examTime: "14:00 - 15:30",
    followUpDate: "30/04/2024",
    diagnosis: ["Hở van tim.", "Có dấu hiệu mỡ trong máu"],
    doctorNotes: ["Nên uống nhiều nước hơn", "Không hút thuốc", "Không suy nghĩ nhiều, giữ đầu óc thư giãn"],
    testResults: [
      {
        name: "File 1",
        fileUrl: "/placeholder.pdf",
      },
      {
        name: "File 2",
        fileUrl: "/placeholder.pdf",
      },
    ],
    codes: {
      appointmentCode: "312893714",
      transactionCode: "31283781293714",
      patientCode: "47298347293847",
    },
  },
  {
    id: "5",
    date: "Thứ 6, 19/04/2024",
    time: "10:00 - 10:30 AM",
    doctorName: "BS. Lê Thị Hương",
    specialty: "Nội tiết",
    imageUrl: "/placeholder.svg?height=60&width=60",
    status: "completed",
    department: "Nội tiết",
    room: "Phòng 22 - Tầng 2 Khu A",
    queueNumber: 15,
    patientName: "LÊ THIỆN NHI",
    patientBirthday: "28/04/2004",
    patientGender: "Nữ",
    patientLocation: "Cà Mau",
    appointmentFee: "180.000 VND",
    examTime: "10:15 - 11:00",
    followUpDate: "19/05/2024",
    diagnosis: ["Rối loạn nội tiết tố"],
    doctorNotes: ["Tập thể dục đều đặn", "Ăn uống điều độ", "Hạn chế đồ ngọt"],
    testResults: [
      {
        name: "Kết quả xét nghiệm máu",
        fileUrl: "/placeholder.pdf",
      },
    ],
    codes: {
      appointmentCode: "312893715",
      transactionCode: "31283781293715",
      patientCode: "47298347293847",
    },
  },
]

// Mock Doctors
export const mockDoctors: Doctor[] = [
  {
    id: "1",
    name: "ThS BS. Trần Ngọc Anh Thơ",
    specialty: "Da khoa",
    imageUrl: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    experience: "10 năm",
    availability: ["Thứ 2", "Thứ 4", "Thứ 6"],
  },
  {
    id: "2",
    name: "BSCKI. Huỳnh Văn Thiều",
    specialty: "Sản nhi",
    imageUrl: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    experience: "15 năm",
    availability: ["Thứ 3", "Thứ 5", "Thứ 7"],
  },
  {
    id: "3",
    name: "BSCKII. TRẦN ĐỖ PHƯƠNG NHI",
    specialty: "Tim mạch",
    imageUrl: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    experience: "20 năm",
    availability: ["Thứ 2", "Thứ 3", "Thứ 5"],
  },
]